name: study_helper
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.5.4+1
  cupertino_icons: ^0.1.3
  expandable_card: ^0.0.3+1
  flutter_easyloading: ^3.0.0
  flutter_icons: ^1.1.0
  path: ^1.8.0
  provider: ^4.3.2+1xw
  shared_preferences: ^0.5.10
  slide_popup_dialog: ^0.0.2
  smooth_star_rating: ^1.1.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icon.png

module:
  androidX: true
