name: study_helper
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.5.4+1
  cupertino_icons: ^0.1.3
  disk_space: ^0.0.3
  downloads_path_provider: ^0.1.0
  file_chooser: ^0.1.6
  file_picker_cross: ^4.2.6
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.8.0
  path_provider: ^1.6.14
  provider: ^4.3.2+1xw
  shared_preferences: ^0.5.10
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icon.png

module:
  androidX: true
